### ISSUE TITLE
Hello I am Getting error after some time 

### ISSUE THREAD

**Issue by tomriddle54** [AdamCox9/Steemit-Follow-Bot#1]
This is the error don't know why i am getting this 
```
[ 'follow',
  { follower: 'kamesh', following: 'haywiree', what: [ 'blog' ] } ]
Unhandled rejection Error: not opened
    at WebSocket.send (/home/ubuntu/kemash/node_modules/ws/lib/WebSocket.js:360:18)
    at /home/ubuntu/kemash/node_modules/steem/lib/api/transports/ws.js:135:19
    at tryCatcher (/home/ubuntu/kemash/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/kemash/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ubuntu/kemash/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/ubuntu/kemash/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/home/ubuntu/kemash/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/ubuntu/kemash/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ubuntu/kemash/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
[ 'follow',
  { follower: 'kamesh', following: 'hayzed1', what: [ 'blog' ] } ]
Unhandled rejection Error: not opened
    at WebSocket.send (/home/ubuntu/kemash/node_modules/ws/lib/WebSocket.js:360:18)
    at /home/ubuntu/kemash/node_modules/steem/lib/api/transports/ws.js:135:19
    at tryCatcher (/home/ubuntu/kemash/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/kemash/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ubuntu/kemash/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/ubuntu/kemash/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/home/ubuntu/kemash/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/ubuntu/kemash/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ubuntu/kemash/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)

```

**Comment by AdamCox9** [comment]
I'm pretty sure you got rate limited by the server you are sending your
requests to.

Adam Cox
